# Use the official Python image as the base
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file 
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . . 

# Specify the command to run when the container starts
ENTRYPOINT [ "python", "-u" ]
CMD [ "main.py" ]